# Generated by Django 5.2.1 on 2025-06-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(verbose_name='Бюджет проекта (₽)')),
                ('duration', models.IntegerField(verbose_name='Сроки реализации (мес)')),
                ('novelty', models.IntegerField(verbose_name='Новизна проекта')),
                ('experience', models.IntegerField(verbose_name='Опыт менеджера (лет)')),
                ('contractors', models.IntegerField(verbose_name='Доля подрядчиков (%)')),
                ('risk_plan', models.IntegerField(verbose_name='Развитость плана управления рисками (0–10)')),
                ('time_buffer', models.IntegerField(verbose_name='Запас по срокам (%)')),
                ('cost_buffer', models.IntegerField(verbose_name='Запас по бюджету (%)')),
                ('user_score', models.FloatField(verbose_name='RiskScore до оптимизации')),
                ('optimized_score', models.FloatField(verbose_name='RiskScore после GWO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Оценка риска проекта',
                'verbose_name_plural': 'Оценки рисков проектов',
            },
        ),
    ]
